name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: sbt
    - name: Coursier
      shell: bash
      run: |
        curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs
        chmod +x cs
        eval "$(./cs setup --env)"
    - name: Bloop
      shell: bash
      run: |
        eval "$(./cs bootstrap bloop --standalone -o bloop)"
    - name: Test
      shell: bash
      run: make compile
    - name: Test
      shell: bash
      run: make test-unit
    - name: Test
      shell: bash
      run: make test-e2e